# Generated by Django 5.2.5 on 2025-08-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_document_file_event_initiativesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='initiative_type',
            field=models.CharField(choices=[('initiatives', 'Initiatives'), ('workshop', 'Workshop'), ('sessions', 'Sessions'), ('community_event', 'Community Event'), ('other', 'Others')], default='other', max_length=20),
        ),
    ]
